export const GET_POKEMON_REQUEST = 'GET_POKEMON_REQUEST'
export const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS'
export const GET_POKEMON_FAIL = 'GET_POKEMON_FAIL'
export const SET_POKEMON = 'SET_POKEMON'
